### ISSUE TITLE
Marking items un-satisfied

### ISSUE THREAD

**Issue by dylanz** [strongdm/comply#77]
I'm just starting here, and after initializing the project, I want to mark all items unsatisfied until I've had a chance to go through them all.  I see there's a .Satisfied that determines if it is or not, but I can't tell for the life of me how to set that true or not.  I guess my questions are:

- How do I mark all the items as unsatisfied?
- Would a good first step in the process be to manually mark things as unsatisfied (or by default, not sure), then to work through the list?

**Comment by joepurdy** [comment]
@dylanz I opened a PR that would default newly initialized compliance projects to show controls as un-satisfied.

Just as a heads up in case my PR doesn't land in comply or you want to manually un-satisfy controls you can simply comment out the `satisfies` front-matter on all the policies and narratives that you haven't implemented.

For example, instead of this:
```
name: Organizational Narrative
acronym: ON
satisfies:
  TSC:
    - CC1.2
    - CC1.3
    - CC1.4
    - CC1.5
    - CC3.1
    - CC3.2
    - CC3.3
majorRevisions:
  - date: Jun 1 2018
    comment: Initial document
---
```

Comment out the `satisfies` front matter like this:
```
name: Organizational Narrative
acronym: ON
satisfies:
<!-- satisfies:
  TSC:
    - CC1.2
    - CC1.3
    - CC1.4
    - CC1.5
    - CC3.1
    - CC3.2
    - CC3.3 -->
majorRevisions:
  - date: Jun 1 2018
    comment: Initial document
---
```

This will ensure comply doesn't register these criteria as satisfied. Once the policy is implemented you can uncomment the `satisfies` front matter and that will mark controls as satisfied.
